version: '3'

services:
  node0:
    container_name: node0
    image: glodnet/gnchaind
    environment:
      NODE_HOSTS:
      RECOVER: "gossip wheel net riot retreat arrest ozone dragon funny undo bulb visa victory label slim domain network wage suit peanut tattoo text venture answer"
      GNCHAIND_MONIKER: "node0"
      GNCHAIND_API_ENABLE: "true"
    ports:
      - "1317:1317"
      - "9090:9090"
      - "26656-26657:26656-26657"
    command: sh -c "/wait && /init.sh && /run.sh"
    volumes:
      - ./chain.yml:/root/chain.yml
      - node-data:/root/.gnchain
volumes:
  node-data: