version: "3.6"

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: fcd
  fcd-collector:
    image: terramoney/fcd:1.0.11
    restart: always
    depends_on:
      - postgres
    env_file: fcd.env
    command: collector
  fcd-api:
    image: terramoney/fcd:1.0.11
    depends_on:
      - postgres
    ports:
      - 3060:3060
    env_file: fcd.env
    command: start
