// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chain/identity/identity.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	strconv "strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PubKeyAlgorithm defines the algorithm names for the public key
type PubKeyAlgorithm int32

const (
	// UnknownPubKeyAlgorithm defines an unknown algorithm name
	UnknownPubKeyAlgorithm PubKeyAlgorithm = 0
	// RSA defines a RSA algorithm name
	RSA PubKeyAlgorithm = 1
	// DSA defines a DSA algorithm name.
	DSA PubKeyAlgorithm = 2
	// ECDSA defines an ECDSA algorithm name.
	ECDSA PubKeyAlgorithm = 3
	// ED25519 defines an ED25519 algorithm name.
	ED25519 PubKeyAlgorithm = 4
	// SM2 defines an SM2 algorithm name.
	SM2 PubKeyAlgorithm = 5
)

var PubKeyAlgorithm_name = map[int32]string{
	0: "UnknownPubKeyAlgorithm",
	1: "RSA",
	2: "DSA",
	3: "ECDSA",
	4: "ED25519",
	5: "SM2",
}

var PubKeyAlgorithm_value = map[string]int32{
	"UnknownPubKeyAlgorithm": 0,
	"RSA":                    1,
	"DSA":                    2,
	"ECDSA":                  3,
	"ED25519":                4,
	"SM2":                    5,
}

func (PubKeyAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_02acdfc7e422fb87, []int{0}
}

type Identity struct {
	Address     string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Certificate string `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Parent      string `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Data        string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Creator     string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_02acdfc7e422fb87, []int{0}
}
func (m *Identity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return m.Size()
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Identity) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *Identity) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Identity) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Identity) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// PubKey represents a public key along with the corresponding algorithm
type PubKeyInfo struct {
	PubKey    string          `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pubkey" yaml:"pubkey"`
	Algorithm PubKeyAlgorithm `protobuf:"varint,2,opt,name=algorithm,proto3,enum=glodnet.chain.identity.PubKeyAlgorithm" json:"algorithm,omitempty"`
}

func (m *PubKeyInfo) Reset()         { *m = PubKeyInfo{} }
func (m *PubKeyInfo) String() string { return proto.CompactTextString(m) }
func (*PubKeyInfo) ProtoMessage()    {}
func (*PubKeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_02acdfc7e422fb87, []int{1}
}
func (m *PubKeyInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PubKeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PubKeyInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PubKeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubKeyInfo.Merge(m, src)
}
func (m *PubKeyInfo) XXX_Size() int {
	return m.Size()
}
func (m *PubKeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PubKeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PubKeyInfo proto.InternalMessageInfo

func (m *PubKeyInfo) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *PubKeyInfo) GetAlgorithm() PubKeyAlgorithm {
	if m != nil {
		return m.Algorithm
	}
	return UnknownPubKeyAlgorithm
}

func init() {
	proto.RegisterEnum("glodnet.chain.identity.PubKeyAlgorithm", PubKeyAlgorithm_name, PubKeyAlgorithm_value)
	proto.RegisterType((*Identity)(nil), "glodnet.chain.identity.Identity")
	proto.RegisterType((*PubKeyInfo)(nil), "glodnet.chain.identity.PubKeyInfo")
}

func init() { proto.RegisterFile("chain/identity/identity.proto", fileDescriptor_02acdfc7e422fb87) }

var fileDescriptor_02acdfc7e422fb87 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x8b, 0xd3, 0x40,
	0x18, 0xce, 0x6c, 0xbf, 0xec, 0xac, 0x1f, 0x61, 0x58, 0x4a, 0x88, 0x38, 0x0d, 0xbd, 0xf8, 0x71,
	0x48, 0xb1, 0xba, 0x82, 0x7b, 0xeb, 0x6e, 0x7b, 0x58, 0x96, 0x05, 0x69, 0xf0, 0xe2, 0x45, 0x26,
	0xc9, 0x6c, 0x1a, 0xda, 0xce, 0x84, 0x74, 0x8a, 0xe6, 0x1f, 0x48, 0x10, 0xf4, 0x0f, 0x04, 0x04,
	0xf7, 0xe0, 0xd1, 0x3f, 0xe0, 0xdd, 0xe3, 0x1e, 0x3d, 0x2d, 0xd2, 0x5e, 0xc4, 0xa3, 0xbf, 0x40,
	0x66, 0x26, 0x71, 0xa5, 0xe8, 0xed, 0xf9, 0x9a, 0x79, 0x5f, 0x5e, 0x1e, 0x78, 0x27, 0x98, 0x92,
	0x98, 0xf5, 0xe3, 0x90, 0x32, 0x11, 0x8b, 0xec, 0x0f, 0x70, 0x93, 0x94, 0x0b, 0x8e, 0x3a, 0xd1,
	0x9c, 0x87, 0x8c, 0x0a, 0x57, 0xc5, 0xdc, 0xca, 0xb5, 0xf7, 0x22, 0x1e, 0x71, 0x15, 0xe9, 0x4b,
	0xa4, 0xd3, 0xbd, 0xb7, 0x00, 0x5e, 0x3b, 0x2e, 0x23, 0xc8, 0x82, 0x2d, 0x12, 0x86, 0x29, 0x5d,
	0x2e, 0x2d, 0xe0, 0x80, 0x7b, 0xed, 0x49, 0x45, 0x91, 0x03, 0x77, 0x03, 0x9a, 0x8a, 0xf8, 0x2c,
	0x0e, 0x88, 0xa0, 0xd6, 0x8e, 0x72, 0xff, 0x96, 0x50, 0x07, 0x36, 0x13, 0x92, 0x52, 0x26, 0xac,
	0x9a, 0x32, 0x4b, 0x86, 0x10, 0xac, 0x87, 0x44, 0x10, 0xab, 0xae, 0x54, 0x85, 0xe5, 0x9c, 0x20,
	0xa5, 0x44, 0xf0, 0xd4, 0x6a, 0xe8, 0x39, 0x25, 0xed, 0xbd, 0x03, 0x10, 0x3e, 0x5b, 0xf9, 0x27,
	0x34, 0x3b, 0x66, 0x67, 0x1c, 0x3d, 0x86, 0xad, 0x64, 0xe5, 0xbf, 0x9c, 0xd1, 0x4c, 0x2f, 0x74,
	0x78, 0xfb, 0xe7, 0x65, 0xb7, 0x99, 0xac, 0xfc, 0x19, 0xcd, 0x7e, 0x5d, 0x76, 0x6f, 0x64, 0x64,
	0x31, 0x3f, 0xe8, 0x69, 0xde, 0x9b, 0x48, 0xe3, 0x84, 0x66, 0x68, 0x0c, 0xdb, 0x64, 0x1e, 0xf1,
	0x34, 0x16, 0xd3, 0x85, 0x5a, 0xf5, 0xe6, 0xe0, 0xae, 0xfb, 0xef, 0xab, 0xb8, 0x7a, 0xd8, 0xb0,
	0x8a, 0x4f, 0xae, 0x5e, 0x1e, 0xd4, 0x7f, 0x7c, 0xe8, 0x82, 0x07, 0x5f, 0x00, 0xbc, 0xb5, 0x15,
	0x42, 0x4f, 0x60, 0xe7, 0x39, 0x9b, 0x31, 0xfe, 0x8a, 0x6d, 0x39, 0xa6, 0x61, 0xdb, 0x79, 0xe1,
	0xfc, 0xc7, 0x45, 0x26, 0xac, 0x4d, 0xbc, 0xa1, 0x09, 0xec, 0x56, 0x5e, 0x38, 0x12, 0x4a, 0x65,
	0xe4, 0x0d, 0xcd, 0x1d, 0xad, 0x8c, 0xbc, 0x21, 0xda, 0x83, 0x8d, 0xf1, 0x91, 0xd4, 0x6a, 0x76,
	0x3b, 0x2f, 0x1c, 0x4d, 0xe4, 0xc5, 0xc6, 0xa3, 0xc1, 0xfe, 0xfe, 0xc3, 0xa7, 0x66, 0xdd, 0xde,
	0xcd, 0x0b, 0xa7, 0xa2, 0xf2, 0x07, 0xef, 0x74, 0x60, 0x36, 0xf4, 0x0f, 0xde, 0xe9, 0xc0, 0xbe,
	0xfe, 0xe6, 0x23, 0x36, 0x3e, 0x9d, 0x63, 0xe3, 0xf3, 0x39, 0x06, 0x87, 0x47, 0x5f, 0xd7, 0x18,
	0x5c, 0xac, 0x31, 0xf8, 0xbe, 0xc6, 0xe0, 0xfd, 0x06, 0x1b, 0x17, 0x1b, 0x6c, 0x7c, 0xdb, 0x60,
	0xe3, 0xc5, 0xfd, 0x28, 0x16, 0xd3, 0x95, 0xef, 0x06, 0x7c, 0xd1, 0x2f, 0xaf, 0xd3, 0xd7, 0xd5,
	0x7a, 0x7d, 0x55, 0x2e, 0x91, 0x25, 0x74, 0xe9, 0x37, 0x55, 0x59, 0x1e, 0xfd, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x9b, 0x4b, 0x5a, 0x5d, 0x7b, 0x02, 0x00, 0x00,
}

func (x PubKeyAlgorithm) String() string {
	s, ok := PubKeyAlgorithm_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *PubKeyInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PubKeyInfo)
	if !ok {
		that2, ok := that.(PubKeyInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PubKey != that1.PubKey {
		return false
	}
	if this.Algorithm != that1.Algorithm {
		return false
	}
	return true
}
func (m *Identity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Identity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Identity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Parent) > 0 {
		i -= len(m.Parent)
		copy(dAtA[i:], m.Parent)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.Parent)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Certificate) > 0 {
		i -= len(m.Certificate)
		copy(dAtA[i:], m.Certificate)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.Certificate)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PubKeyInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PubKeyInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PubKeyInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Algorithm != 0 {
		i = encodeVarintIdentity(dAtA, i, uint64(m.Algorithm))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIdentity(dAtA []byte, offset int, v uint64) int {
	offset -= sovIdentity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Identity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	l = len(m.Certificate)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	l = len(m.Parent)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	return n
}

func (m *PubKeyInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	if m.Algorithm != 0 {
		n += 1 + sovIdentity(uint64(m.Algorithm))
	}
	return n
}

func sovIdentity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIdentity(x uint64) (n int) {
	return sovIdentity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Identity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Identity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Identity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certificate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Certificate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Parent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PubKeyInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PubKeyInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PubKeyInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Algorithm", wireType)
			}
			m.Algorithm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Algorithm |= PubKeyAlgorithm(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIdentity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIdentity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIdentity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIdentity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIdentity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIdentity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIdentity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIdentity = fmt.Errorf("proto: unexpected end of group")
)
